import type { Metadata } from "next";
import { Audiowide, Inter, Staatliches } from "next/font/google";
import "./globals.css";

import { StoreProvider } from "@/store/StoreProvider";
import { Dialog } from "@/components";

const audiowide = Audiowide({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<StoreProvider>
    <html lang="en">
      <body className={audiowide.className}>
          {children}
          <Dialog />
        </body>
    </html>
  </StoreProvider>);
}
