import type { Metadata } from "next";
//import { Archivo_Black, Audiowide, Inter, Lilita_One, Staatliches } from "next/font/google";

import { StoreProvider } from "@/store/StoreProvider";
import { Dialog } from "@/components";

import localFont from 'next/font/local';
import "./globals.css";

const impact = localFont({
  src: [
    { path: '../public/fonts/impact.ttf', weight: '400', style: 'normal' },
    { path: '../public/fonts/Impacted.ttf', weight: '700', style: 'normal' },
    { path: '../public/fonts/unicode.impact.ttf', weight: '400', style: 'italic' }
  ],
  variable: '--font-impact'
});

//const archivo_black = Archivo_Black({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<StoreProvider>
    <html lang="en">
      <body className={impact.className} style={{ overflow: "hidden" }}>
        {children}
        {/*<Dialog />*/}
      </body>
    </html>
  </StoreProvider>);
}
